import Foundation
import FirebaseCore
import FirebaseAILogic

// MARK: - Gemini Service Errors

/// Errors originating from the Gemini AI service.
public enum GeminiError: LocalizedError, Equatable, Sendable {
    case apiKeyMissing
    case firebaseNotConfigured
    case invalidResponse(String)
    case rateLimited
    case networkError(String)
    
    public var errorDescription: String? {
        switch self {
        case .apiKeyMissing:
            return "Gemini API key is not configured. Falling back to on-device offline reasoning."
        case .firebaseNotConfigured:
            return "Firebase AI SDK is not configured. Ensure GoogleService-Info.plist or API key is set."
        case .invalidResponse(let msg):
            return "Gemini response could not be parsed: \(msg)"
        case .rateLimited:
            return "Gemini API rate limit reached. Please wait a moment."
        case .networkError(let msg):
            return "Gemini network error: \(msg)"
        }
    }
}

/// Enforces strict length limits on Gemini-generated narratives.
public enum GeminiWordLimitEnforcer {
    public static func trimTo200Words(_ text: String) -> String {
        let words = text.split(whereSeparator: \.isWhitespace)
        if words.count <= 200 {
            return text
        }
        let truncatedWords = words.prefix(200).joined(separator: " ")
        if let lastPeriod = truncatedWords.lastIndex(where: { $0 == "." || $0 == "!" || $0 == "?" }) {
            return String(truncatedWords[...lastPeriod])
        }
        return truncatedWords + "..."
    }
}

// MARK: - Train Recommendation Result

/// Recommendation output generated by Google Gemini when evaluating multiple live train candidates.
public struct TrainRecommendationResult: Sendable, Codable, Equatable {
    public let recommendedTrainNumber: String
    public let recommendedClassCode: String?
    public let rationale: String
    public let topThreeTrainNumbers: [String]
    public let alternativeNotes: [String: String]
    
    public init(
        recommendedTrainNumber: String,
        recommendedClassCode: String? = nil,
        rationale: String,
        topThreeTrainNumbers: [String] = [],
        alternativeNotes: [String: String] = [:]
    ) {
        self.recommendedTrainNumber = recommendedTrainNumber
        self.recommendedClassCode = recommendedClassCode
        self.rationale = rationale
        self.topThreeTrainNumbers = topThreeTrainNumbers
        self.alternativeNotes = alternativeNotes
    }
}

/// Recommendation output generated by Google Gemini when evaluating connecting train journeys.
public struct ConnectingJourneyRecommendationResult: Sendable, Codable, Equatable {
    public let recommendedJourneyId: String
    public let rationale: String
    public let topThreeJourneyIds: [String]
    public let alternativeNotes: [String: String]
    
    public init(
        recommendedJourneyId: String,
        rationale: String,
        topThreeJourneyIds: [String] = [],
        alternativeNotes: [String: String] = [:]
    ) {
        self.recommendedJourneyId = recommendedJourneyId
        self.rationale = rationale
        self.topThreeJourneyIds = topThreeJourneyIds
        self.alternativeNotes = alternativeNotes
    }
}

// MARK: - Gemini Service Protocol

/// Protocol defining the contract for Gemini Generative AI operations.
public protocol GeminiServiceProtocol: Sendable {
    func parseTripPrompt(_ prompt: String) async throws -> TripRequest
    func generateItineraryNarrative(for itinerary: TripItinerary, request: TripRequest) async throws -> String
    func generateItineraryNarrativeStream(for itinerary: TripItinerary, request: TripRequest) async throws -> AsyncThrowingStream<String, Error>
    func handleConversationalModification(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) async throws -> ItineraryModificationResult
    func recommendTrain(
        trains: [TrainCandidate],
        request: TripRequest
    ) async throws -> TrainRecommendationResult
    func recommendConnectingJourney(
        journeys: [TrainConnectingJourney],
        request: TripRequest
    ) async throws -> ConnectingJourneyRecommendationResult
}

public extension GeminiServiceProtocol {
    func generateItineraryNarrativeStream(for itinerary: TripItinerary, request: TripRequest) async throws -> AsyncThrowingStream<String, Error> {
        let narrative = try await generateItineraryNarrative(for: itinerary, request: request)
        return AsyncThrowingStream { continuation in
            continuation.yield(narrative)
            continuation.finish()
        }
    }
}

// MARK: - Firebase AI SDK Service Implementation

/// Live Gemini generative AI service powered by the official Firebase AI SDK (`FirebaseAI`).
///
/// **Architectural Guarantees:**
/// 1. Uses official Google Firebase AI Logic client SDK.
/// 2. Enforces structured JSON output via `GenerationConfig(responseMIMEType: "application/json")`.
/// 3. Strict hallucination protection: conversational modifications reason over genuine candidate IDs.
/// 4. Zero-crash safety: automatically routes to offline fallback if Firebase is uninitialized.
public final class FirebaseGeminiService: GeminiServiceProtocol, Sendable {
    public let modelName: String
    private let fallback: FallbackGeminiService
    
    public init(
        modelName: String = "gemini-2.5-flash",
        fallback: FallbackGeminiService = FallbackGeminiService()
    ) {
        self.modelName = modelName
        self.fallback = fallback
    }
    
    /// Safely ensures Firebase is configured before accessing `FirebaseAI`.
    private func ensureFirebaseConfigured() -> Bool {
        return AppConfiguration.shared.configureFirebaseIfNeeded()
    }
    
    /// Strict output schema defining the expected JSON structure for parsed travel requests.
    public static var tripRequestSchema: Schema {
        return Schema.object(
            properties: [
                "destination": .string(description: "Destination city or tourist region name, capitalized"),
                "origin": .string(description: "Departure origin city, defaults to 'Delhi' if unspecified"),
                "numberOfDays": .integer(description: "Total trip duration in days (positive integer)"),
                "travelersCount": .integer(description: "Total count of traveling guests (positive integer)"),
                "groupType": .enumeration(values: ["Solo", "Couple", "Friends", "Family", "Business"], description: "Dynamic of the travel group"),
                "budget": .double(description: "Total monetary budget for the trip"),
                "currency": .string(description: "ISO currency code, e.g. INR, USD, EUR, GBP"),
                "tripType": .enumeration(values: ["roundTrip", "oneWay"], description: "Type of trip journey"),
                "preferences": .array(items: .string(), description: "Preferences: Nature, Culture, Adventure, Foodie, Shopping, Luxury, Budget-friendly, Relaxation")
            ],
            optionalProperties: ["origin", "tripType", "preferences"]
        )
    }
    
    private func getGenerativeModel(
        systemInstruction: String? = nil,
        responseJSON: Bool = false,
        responseSchema: Schema? = nil
    ) -> GenerativeModel? {
        guard ensureFirebaseConfigured() else { return nil }
        
        let ai = FirebaseAI.firebaseAI(backend: .googleAI())
        let config = GenerationConfig(
            temperature: 0.1,
            responseMIMEType: (responseJSON || responseSchema != nil) ? "application/json" : "text/plain",
            responseSchema: responseSchema
        )
        
        let systemContent: ModelContent? = systemInstruction.map {
            ModelContent(role: "system", parts: $0)
        }
        
        return ai.generativeModel(
            modelName: modelName,
            generationConfig: config,
            systemInstruction: systemContent
        )
    }
    
    // MARK: - Natural Language Understanding (Prompt Parsing)
    
    public func parseTripPrompt(_ prompt: String) async throws -> TripRequest {
        let startTime = Date()
        let systemPrompt = "Extract travel parameters strictly conforming to the structured response schema."
        
        if let model = getGenerativeModel(systemInstruction: systemPrompt, responseSchema: Self.tripRequestSchema) {
            do {
                let response = try await model.generateContent(prompt)
                let elapsed = Date().timeIntervalSince(startTime)
                if let text = response.text, let parsed = Self.decodeTripRequest(from: text) {
                    AppLogger.shared.logGeminiResponse(
                        action: "parseTripPrompt (Structured Schema)",
                        model: modelName,
                        duration: elapsed,
                        promptSnippet: prompt,
                        responseSnippet: "Parsed destination: \(parsed.destination), days: \(parsed.numberOfDays), travelers: \(parsed.travelersCount), budget: \(parsed.currency) \(Int(parsed.budget))"
                    )
                    return parsed
                }
            } catch {
                AppLogger.shared.logGeminiError(
                    action: "parseTripPrompt",
                    model: modelName,
                    error: error,
                    fallbackUsed: true,
                    promptSnippet: prompt
                )
            }
        }
        
        // Attempt direct Gemini REST API if key is available before offline fallback
        if let key = AppConfiguration.shared.geminiApiKey, key.count > 10 {
            let direct = GeminiAPIService(apiKey: key, fallback: fallback)
            if let parsed = try? await direct.parseTripPrompt(prompt) {
                return parsed
            }
        }
        
        return try await fallback.parseTripPrompt(prompt)
    }
    
    // MARK: - Grounded Narrative Synthesis
    
    public func generateItineraryNarrative(for itinerary: TripItinerary, request: TripRequest) async throws -> String {
        let startTime = Date()
        let prompt = Self.buildNarrativePrompt(for: itinerary, request: request)
        let systemPrompt = """
        You are an inspiring, grounded travel concierge. Write a concise, compelling itinerary narrative.
        Ground your text strictly in the provided hotel, transit, and daily activity names.
        Do NOT invent prices, tickets, or confirmation numbers.
        CRITICAL CONSTRAINT: Keep your entire response strictly under 200 words.
        """
        
        if let model = getGenerativeModel(systemInstruction: systemPrompt, responseJSON: false) {
            do {
                let response = try await model.generateContent(prompt)
                let elapsed = Date().timeIntervalSince(startTime)
                if let text = response.text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    let narrative = GeminiWordLimitEnforcer.trimTo200Words(text.trimmingCharacters(in: .whitespacesAndNewlines))
                    AppLogger.shared.logGeminiResponse(
                        action: "generateItineraryNarrative",
                        model: modelName,
                        duration: elapsed,
                        promptSnippet: "Itinerary narrative for \(itinerary.destination)",
                        responseSnippet: narrative
                    )
                    return narrative
                }
            } catch {
                AppLogger.shared.logGeminiError(
                    action: "generateItineraryNarrative",
                    model: modelName,
                    error: error,
                    fallbackUsed: true
                )
            }
        }
        
        // Attempt direct Gemini REST API if key is available before offline fallback
        if let key = AppConfiguration.shared.geminiApiKey, key.count > 10 {
            let direct = GeminiAPIService(apiKey: key, fallback: fallback)
            if let directText = try? await direct.generateItineraryNarrative(for: itinerary, request: request),
               !directText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                return GeminiWordLimitEnforcer.trimTo200Words(directText.trimmingCharacters(in: .whitespacesAndNewlines))
            }
        }
        
        return try await fallback.generateItineraryNarrative(for: itinerary, request: request)
    }
    
    public func generateItineraryNarrativeStream(for itinerary: TripItinerary, request: TripRequest) async throws -> AsyncThrowingStream<String, Error> {
        let prompt = Self.buildNarrativePrompt(for: itinerary, request: request)
        let systemPrompt = """
        You are an inspiring, grounded travel concierge. Write a concise, compelling itinerary narrative.
        Ground your text strictly in the provided hotel, transit, and daily activity names.
        Do NOT invent prices, tickets, or confirmation numbers.
        CRITICAL CONSTRAINT: Keep your entire response strictly under 200 words.
        """
        
        if let model = getGenerativeModel(systemInstruction: systemPrompt, responseJSON: false) {
            do {
                let stream = try model.generateContentStream(prompt)
                let fallbackService = self.fallback
                return AsyncThrowingStream { continuation in
                    Task {
                        var didYieldAny = false
                        do {
                            for try await chunk in stream {
                                if let text = chunk.text {
                                    continuation.yield(text)
                                    didYieldAny = true
                                }
                            }
                            continuation.finish()
                        } catch {
                            // If remote streaming fails (e.g. 403 API disabled, quota, or offline), fall back seamlessly
                            if !didYieldAny {
                                if let key = AppConfiguration.shared.geminiApiKey, key.count > 10 {
                                    let direct = GeminiAPIService(apiKey: key, fallback: fallbackService)
                                    if let directText = try? await direct.generateItineraryNarrative(for: itinerary, request: request),
                                       !directText.isEmpty {
                                        continuation.yield(directText)
                                        continuation.finish()
                                        return
                                    }
                                }
                                
                                do {
                                    let fallbackNarrative = try await fallbackService.generateItineraryNarrative(for: itinerary, request: request)
                                    continuation.yield(fallbackNarrative)
                                    continuation.finish()
                                } catch {
                                    continuation.finish(throwing: error)
                                }
                            } else {
                                continuation.finish()
                            }
                        }
                    }
                }
            } catch {
                // Fallback to single-yield stream
            }
        }
        
        // Attempt direct REST before static offline fallback
        if let key = AppConfiguration.shared.geminiApiKey, key.count > 10 {
            let direct = GeminiAPIService(apiKey: key, fallback: fallback)
            if let directText = try? await direct.generateItineraryNarrative(for: itinerary, request: request),
               !directText.isEmpty {
                return AsyncThrowingStream { continuation in
                    continuation.yield(directText)
                    continuation.finish()
                }
            }
        }
        
        let single = try await fallback.generateItineraryNarrative(for: itinerary, request: request)
        return AsyncThrowingStream { continuation in
            continuation.yield(single)
            continuation.finish()
        }
    }
    
    // MARK: - Conversational Modification (Grounded Alternative Swaps)
    
    public func handleConversationalModification(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) async throws -> ItineraryModificationResult {
        let startTime = Date()
        let prompt = Self.buildModificationPrompt(
            instruction: instruction,
            currentItinerary: currentItinerary,
            candidatePool: candidatePool
        )
        
        let systemPrompt = """
        You are an AI travel itinerary modifier. The user wants to modify their travel plan.
        You are provided their current selections and real alternative candidate options.
        Select alternatives strictly from the given IDs. Do not invent hotels or transit options.
        Output ONLY valid JSON with keys:
        - "action": "swapHotel", "swapTransport", or "none"
        - "selectedHotelId": string (UUID string of candidate hotel to swap to, or null)
        - "selectedTransportId": string (UUID string of candidate transport to swap to, or null)
        - "aiExplanation": string (warm explanation of the swap and budget impact)
        """
        
        if let model = getGenerativeModel(systemInstruction: systemPrompt, responseJSON: true) {
            do {
                let response = try await model.generateContent(prompt)
                let elapsed = Date().timeIntervalSince(startTime)
                if let text = response.text,
                   let result = Self.applyModification(
                    jsonText: text,
                    currentItinerary: currentItinerary,
                    candidatePool: candidatePool
                   ) {
                    AppLogger.shared.logGeminiResponse(
                        action: "handleConversationalModification",
                        model: modelName,
                        duration: elapsed,
                        promptSnippet: instruction,
                        responseSnippet: result.aiExplanation
                    )
                    return result
                }
            } catch {
                AppLogger.shared.logGeminiError(
                    action: "handleConversationalModification",
                    model: modelName,
                    error: error,
                    fallbackUsed: true,
                    promptSnippet: instruction
                )
            }
        }
        
        if let key = AppConfiguration.shared.geminiApiKey, key.count > 10 {
            let direct = GeminiAPIService(apiKey: key, fallback: fallback)
            if let result = try? await direct.handleConversationalModification(
                instruction: instruction,
                currentItinerary: currentItinerary,
                candidatePool: candidatePool
            ) {
                return result
            }
        }
        
        return try await fallback.handleConversationalModification(
            instruction: instruction,
            currentItinerary: currentItinerary,
            candidatePool: candidatePool
        )
    }
    
    // MARK: - Helpers
    
    private static func decodeTripRequest(from jsonText: String) -> TripRequest? {
        let cleaned = jsonText.replacingOccurrences(of: "```json", with: "")
            .replacingOccurrences(of: "```", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        
        guard let data = cleaned.data(using: .utf8),
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let destination = dict["destination"] as? String, !destination.isEmpty else {
            return nil
        }
        
        let origin = dict["origin"] as? String ?? "Delhi"
        let days = max(1, dict["numberOfDays"] as? Int ?? 4)
        let travelers = max(1, dict["travelersCount"] as? Int ?? 2)
        let budget = max(1000.0, dict["budget"] as? Double ?? 40000.0)
        let currency = dict["currency"] as? String ?? "INR"
        let groupRaw = dict["groupType"] as? String ?? "Friends"
        let groupType = GroupType(rawValue: groupRaw) ?? .friends
        let tripRaw = dict["tripType"] as? String ?? "roundTrip"
        let tripType: TripType = tripRaw.lowercased().contains("one") ? .oneWay : .roundTrip
        
        var preferences: Set<TravelPreference> = []
        if let prefsArray = dict["preferences"] as? [String] {
            for raw in prefsArray {
                if let match = TravelPreference.allCases.first(where: { $0.rawValue.caseInsensitiveCompare(raw) == .orderedSame }) {
                    preferences.insert(match)
                }
            }
        }
        if preferences.isEmpty {
            preferences = [.nature, .relaxation]
        }
        
        return TripRequest(
            origin: origin,
            destination: destination,
            numberOfDays: days,
            travelersCount: travelers,
            groupType: groupType,
            budget: budget,
            currency: currency,
            tripType: tripType,
            preferences: preferences
        )
    }
    
    private static func buildNarrativePrompt(for itinerary: TripItinerary, request: TripRequest) -> String {
        let hotelName = itinerary.selectedHotel?.name ?? "Handpicked Lodging"
        let hotelScore = itinerary.selectedHotel.map { String(format: "%.1f★", $0.reviewScore) } ?? "4.5★"
        let transportTitle = itinerary.selectedTransportation?.title ?? "Express Transit"
        let transportMode = itinerary.selectedTransportation?.mode.rawValue ?? "Transit"
        
        let activitiesSummary = itinerary.days.prefix(3).map { day in
            let places = day.activities.map(\.place.name).joined(separator: ", ")
            return "Day \(day.dayNumber): \(places.isEmpty ? "Local sights & exploration" : places)"
        }.joined(separator: "; ")
        
        return """
        Trip: \(request.numberOfDays) days to \(request.destination) from \(request.origin)
        Party: \(request.travelersCount) (\(request.groupType.rawValue) dynamic)
        Budget: \(request.currency) \(Int(request.budget)) (Planned spend: \(request.currency) \(Int(itinerary.totalEstimatedCost)))
        Transit: \(transportMode) - \(transportTitle)
        Stay: \(hotelName) (\(hotelScore))
        Highlights: \(activitiesSummary)
        CRITICAL CONSTRAINT: Keep your entire itinerary narrative response strictly under 200 words.
        """
    }
    
    private static func buildModificationPrompt(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) -> String {
        let currentHotel = currentItinerary.selectedHotel.map {
            "ID: \($0.id), Name: \($0.name), Price/night: \($0.pricePerNight), Rating: \($0.reviewScore)"
        } ?? "None"
        
        let currentTransit = currentItinerary.selectedTransportation.map {
            "ID: \($0.id.uuidString), Mode: \($0.mode.rawValue), Title: \($0.title), Price: \($0.pricePerPerson)"
        } ?? "None"
        
        let candidateHotels = candidatePool.hotels.prefix(6).map {
            "ID: \($0.id), Name: \($0.name), Price/night: \($0.pricePerNight), Rating: \($0.reviewScore), FamilyFriendly: \($0.isFamilyFriendly)"
        }.joined(separator: "\n")
        
        let candidateTransit = candidatePool.transportOptions.prefix(6).map {
            "ID: \($0.id.uuidString), Mode: \($0.mode.rawValue), Title: \($0.title), Price: \($0.pricePerPerson)"
        }.joined(separator: "\n")
        
        return """
        User Request: "\(instruction)"
        Current Stay: \(currentHotel)
        Current Transit: \(currentTransit)

        Available Alternative Hotels:
        \(candidateHotels)

        Available Alternative Transit:
        \(candidateTransit)
        """
    }
    
    private static func applyModification(
        jsonText: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) -> ItineraryModificationResult? {
        let cleaned = jsonText.replacingOccurrences(of: "```json", with: "")
            .replacingOccurrences(of: "```", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        
        guard let data = cleaned.data(using: .utf8),
              let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }
        
        var updated = currentItinerary
        var explanation = dict["aiExplanation"] as? String ?? ""
        let nights = max(1, currentItinerary.numberOfDays - 1)
        
        if let hotelId = dict["selectedHotelId"] as? String,
           let newHotel = candidatePool.hotels.first(where: { $0.id == hotelId }) {
            updated.selectedHotel = newHotel
            if explanation.isEmpty {
                explanation = "Swapped accommodation to '\(newHotel.name)'."
            }
        }
        
        if let transportId = dict["selectedTransportId"] as? String,
           let newTransport = candidatePool.transportOptions.first(where: { $0.id.uuidString == transportId }) {
            updated.selectedTransportation = newTransport
            if explanation.isEmpty {
                explanation = "Swapped transit to '\(newTransport.title)'."
            }
        }
        
        // Recalculate total cost
        var cost = 0.0
        if let transport = updated.selectedTransportation {
            cost += transport.totalPrice(for: updated.travelersCount)
        }
        if let hotel = updated.selectedHotel {
            cost += hotel.totalCost(for: updated.travelersCount, nights: nights)
        }
        for day in updated.days {
            cost += day.activities.reduce(0.0) { $0 + ($1.place.entryFee * Double(updated.travelersCount)) }
        }
        updated.totalEstimatedCost = cost
        updated.updatedAt = Date()
        
        return ItineraryModificationResult(updatedItinerary: updated, aiExplanation: explanation)
    }
    
    public func recommendTrain(
        trains: [TrainCandidate],
        request: TripRequest
    ) async throws -> TrainRecommendationResult {
        guard ensureFirebaseConfigured() else {
            return try await fallback.recommendTrain(trains: trains, request: request)
        }
        
        guard !trains.isEmpty else {
            throw GeminiError.invalidResponse("No trains available for recommendation")
        }
        
        let trainSummaries = trains.map { train in
            let faresStr = train.classFares.map { "\($0.classCode): \(request.currency) \(Int($0.totalFare))" }.joined(separator: ", ")
            let depStr = DateFormatter.localizedString(from: train.departureTime, dateStyle: .none, timeStyle: .short)
            let arrStr = DateFormatter.localizedString(from: train.arrivalTime, dateStyle: .none, timeStyle: .short)
            return "- Train #\(train.trainNumber) '\(train.trainName)': Departure \(depStr), Arrival \(arrStr), Duration \(train.durationMinutes)m, Fares: [\(faresStr.isEmpty ? "\(train.seatClass): \(Int(train.pricePerPerson))" : faresStr)]"
        }.joined(separator: "\n")
        
        let prompt = """
        User Travel Context:
        - Route: \(request.origin) to \(request.destination)
        - Group: \(request.travelersCount) travelers (\(request.groupType.rawValue))
        - Budget: \(request.currency) \(Int(request.budget))
        - Pace: \(request.pace.rawValue)
        - Preferences: \(request.preferences.map(\.rawValue).joined(separator: ", "))

        Candidate Direct Trains:
        \(trainSummaries)

        Instructions:
        Evaluate all train options considering:
        - Timing convenience (prefer comfortable daytime or overnight arrival, avoid disruptive late night/early dawn timings).
        - Travel time & speed (Vande Bharat / Shatabdi / Superfast advantages).
        - Available coach classes (2A, 3A, 3E, CC, EC) and group budget comfort.
        1. Select the single best train (#1) and recommend the optimal class code (e.g. 3A, 2A, CC).
        2. Provide a 2-sentence rationale explaining the trade-offs (price vs arrival time vs comfort).
        3. Rank the top 3 train numbers and provide a concise 1-sentence note for each alternative explaining when a traveler might prefer it.

        Respond with JSON:
        {
          "recommendedTrainNumber": "string",
          "recommendedClassCode": "string",
          "rationale": "string",
          "topThreeTrainNumbers": ["string"],
          "alternativeNotes": {
            "<trainNumber>": "string"
          }
        }
        """
        
        if let model = getGenerativeModel(
            systemInstruction: "You are an expert railway transit advisor. Compare the candidate direct trains and recommend the single best train for the user, plus top alternatives with trade-offs.",
            responseJSON: true
        ) {
            do {
                let response = try await model.generateContent(prompt)
                if let text = response.text,
                   let data = text.data(using: .utf8),
                   let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                   let recNumber = json["recommendedTrainNumber"] as? String,
                   let rationale = json["rationale"] as? String {
                    let recClass = json["recommendedClassCode"] as? String
                    let topThree = json["topThreeTrainNumbers"] as? [String] ?? [recNumber]
                    let altNotes = json["alternativeNotes"] as? [String: String] ?? [:]
                    return TrainRecommendationResult(
                        recommendedTrainNumber: recNumber,
                        recommendedClassCode: recClass,
                        rationale: rationale,
                        topThreeTrainNumbers: topThree,
                        alternativeNotes: altNotes
                    )
                }
            } catch {
                AppLogger.shared.warning("[FirebaseGeminiService] recommendTrain failed: \(error.localizedDescription), falling back", category: .pipeline)
            }
        }
        
        return try await fallback.recommendTrain(trains: trains, request: request)
    }
    
    public func recommendConnectingJourney(
        journeys: [TrainConnectingJourney],
        request: TripRequest
    ) async throws -> ConnectingJourneyRecommendationResult {
        guard ensureFirebaseConfigured() else {
            return try await fallback.recommendConnectingJourney(journeys: journeys, request: request)
        }
        
        guard !journeys.isEmpty else {
            throw GeminiError.invalidResponse("No connecting journeys available for recommendation")
        }
        
        let journeySummaries = journeys.map { j in
            let leg1 = j.segments[0]
            let leg2 = j.segments.count > 1 ? j.segments[1] : leg1
            let leg1Fares = leg1.classFares.map { "\($0.classCode): \(request.currency) \(Int($0.totalFare))" }.joined(separator: ", ")
            let leg2Fares = leg2.classFares.map { "\($0.classCode): \(request.currency) \(Int($0.totalFare))" }.joined(separator: ", ")
            let dep1Str = DateFormatter.localizedString(from: leg1.departureTime, dateStyle: .none, timeStyle: .short)
            let arr1Str = DateFormatter.localizedString(from: leg1.arrivalTime, dateStyle: .none, timeStyle: .short)
            let dep2Str = DateFormatter.localizedString(from: leg2.departureTime, dateStyle: .none, timeStyle: .short)
            let arr2Str = DateFormatter.localizedString(from: leg2.arrivalTime, dateStyle: .none, timeStyle: .short)
            
            return """
            - Candidate ID "\(j.id)":
              • Leg 1: Train #\(leg1.trainNumber) '\(leg1.trainName)' (\(leg1.originStation) at \(dep1Str) → \(leg1.destinationStation) at \(arr1Str)). Fares: [\(leg1Fares)]
              • Interchange: \(j.connection.stationName), Layover: \(j.connection.formattedLayover) (\(j.connection.layoverMinutes)m)
              • Leg 2: Train #\(leg2.trainNumber) '\(leg2.trainName)' (\(leg2.originStation) at \(dep2Str) → \(leg2.destinationStation) at \(arr2Str)). Fares: [\(leg2Fares)]
              • Total: \(j.formattedTotalDuration), Total Fare: \(request.currency) \(Int(j.totalFarePerPerson)) / person
            """
        }.joined(separator: "\n\n")
        
        let prompt = """
        User Travel Context:
        - Route: \(request.origin) to \(request.destination)
        - Group: \(request.travelersCount) travelers (\(request.groupType.rawValue))
        - Budget: \(request.currency) \(Int(request.budget))
        - Pace: \(request.pace.rawValue)
        - Preferences: \(request.preferences.map(\.rawValue).joined(separator: ", "))

        Candidate Connecting Journeys:
        \(journeySummaries)

        Instructions:
        Evaluate all connecting train journeys considering:
        - Layover safety and comfort (prefer 90-150 min layovers for hassle-free platform transfer and refreshment, penalize overly rushed or exhausting layovers).
        - Total travel time and schedule convenience (convenient daytime or overnight slots, avoiding inconvenient arrival times).
        - Train speed, comfort, and category (Vande Bharat / Shatabdi / Superfast advantages).
        - Value for money against the allocated budget.
        1. Select the single best connecting journey (#1) by Candidate ID.
        2. Provide a 2-3 sentence trade-off rationale explaining why this journey was chosen (balancing layover safety, comfort, speed, and budget).
        3. Rank top 3 Candidate IDs, with a concise 1-sentence note for each alternative explaining when a traveler might choose it.

        Respond with JSON:
        {
          "recommendedJourneyId": "string",
          "rationale": "string",
          "topThreeJourneyIds": ["string"],
          "alternativeNotes": {
            "<journeyId>": "string"
          }
        }
        """
        
        if let model = getGenerativeModel(
            systemInstruction: "You are an expert railway transit advisor. Compare connecting train options and recommend the optimal journey considering layover safety, comfort, timing, and price.",
            responseJSON: true
        ) {
            do {
                let response = try await model.generateContent(prompt)
                if let text = response.text,
                   let data = text.data(using: .utf8),
                   let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                   let recId = json["recommendedJourneyId"] as? String,
                   let rationale = json["rationale"] as? String {
                    let validIds = Set(journeys.map(\.id))
                    let verifiedRecId = validIds.contains(recId) ? recId : (journeys.first?.id ?? recId)
                    let topThree = (json["topThreeJourneyIds"] as? [String] ?? [verifiedRecId]).filter { validIds.contains($0) }
                    let altNotes = json["alternativeNotes"] as? [String: String] ?? [:]
                    return ConnectingJourneyRecommendationResult(
                        recommendedJourneyId: verifiedRecId,
                        rationale: rationale,
                        topThreeJourneyIds: topThree.isEmpty ? [verifiedRecId] : topThree,
                        alternativeNotes: altNotes
                    )
                }
            } catch {
                AppLogger.shared.warning("[FirebaseGeminiService] recommendConnectingJourney failed: \(error.localizedDescription), falling back", category: .pipeline)
            }
        }
        
        return try await fallback.recommendConnectingJourney(journeys: journeys, request: request)
    }
}

// MARK: - Offline Deterministic NLP & Reasoning Engine

/// Robust Natural Language Understanding and itinerary reasoning engine.
///
/// **Zero-Cloud Resilience:**
/// Guarantees that the app is 100% functional even offline, in airplane mode, or without an active API key.
public final class FallbackGeminiService: GeminiServiceProtocol, Sendable {
    public init() {}
    
    public func parseTripPrompt(_ prompt: String) async throws -> TripRequest {
        let lower = prompt.lowercased()
        
        // 1. Destination Extraction
        var destination = "Shimla"
        let knownDestinations = [
            "shimla", "manali", "goa", "jaipur", "kashmir", "ladakh",
            "udaipur", "ooty", "munnar", "rishikesh", "kerala", "dubai",
            "paris", "tokyo", "bali", "switzerland", "london", "bangalore"
        ]
        
        for dest in knownDestinations {
            if lower.contains(dest) {
                destination = dest.capitalized
                break
            }
        }
        
        // Flexible regex for "to <Destination>" or "in <Destination>"
        if destination == "Shimla" && !lower.contains("shimla") {
            let patterns = [
                #"to\s+([a-zA-Z\s]+?)(?=\s+for|\s+with|\s+under|\s+budget|\s+in|$)"#,
                #"trip\s+to\s+([a-zA-Z\s]+?)(?=\s+for|\s+with|\s+under|\s+budget|$)"#,
                #"visit\s+([a-zA-Z\s]+?)(?=\s+for|\s+with|\s+under|\s+budget|$)"#,
                #"in\s+([a-zA-Z\s]+?)(?=\s+for|\s+with|\s+under|\s+budget|$)"#
            ]
            for pattern in patterns {
                if let match = lower.range(of: pattern, options: .regularExpression) {
                    let matchedStr = String(lower[match])
                    let cleaned = matchedStr
                        .replacingOccurrences(of: "trip to ", with: "")
                        .replacingOccurrences(of: "to ", with: "")
                        .replacingOccurrences(of: "visit ", with: "")
                        .replacingOccurrences(of: "in ", with: "")
                        .trimmingCharacters(in: .whitespaces)
                    if !cleaned.isEmpty && cleaned.count < 30 {
                        destination = cleaned.capitalized
                        break
                    }
                }
            }
        }
        
        // 2. Duration Extraction (e.g. "5 days", "3 nights", "a week", "weekend")
        var days = 5
        if lower.contains("weekend") {
            days = 2
        } else if lower.contains("week") && !lower.contains("weeks") {
            days = 7
        } else if let match = prompt.range(of: #"(\d+)\s*(days|day|nights|night)"#, options: .regularExpression) {
            let numStr = prompt[match].components(separatedBy: CharacterSet.decimalDigits.inverted).joined()
            if let parsed = Int(numStr), parsed > 0 {
                days = parsed
            }
        }
        
        // 3. Travelers & Group Dynamic Extraction
        var travelers = 4
        var groupType: GroupType = .friends
        
        if lower.contains("solo") || lower.contains("myself") || lower.contains("alone") {
            travelers = 1
            groupType = .solo
        } else if lower.contains("couple") || lower.contains("wife") || lower.contains("husband") || lower.contains("partner") {
            travelers = 2
            groupType = .couple
        } else if lower.contains("family") || lower.contains("kids") || lower.contains("parents") || lower.contains("children") {
            groupType = .family
            travelers = max(3, travelers)
        } else if lower.contains("colleague") || lower.contains("business") || lower.contains("conference") {
            groupType = .business
        } else if lower.contains("friend") {
            groupType = .friends
        }
        
        if let match = prompt.range(of: #"(\d+)\s*(friends|travelers|people|adults|persons|guests)"#, options: .regularExpression) {
            let numStr = prompt[match].components(separatedBy: CharacterSet.decimalDigits.inverted).joined()
            if let parsed = Int(numStr), parsed > 0 {
                travelers = parsed
            }
        }
        
        // 4. Budget Extraction
        var budget = 50000.0
        var currency = "INR"
        
        if prompt.contains("$") {
            currency = "USD"
            budget = 1500.0
        } else if prompt.contains("€") {
            currency = "EUR"
            budget = 1400.0
        } else if prompt.contains("£") {
            currency = "GBP"
            budget = 1200.0
        }
        
        if let match = prompt.range(of: #"[₹$€£]?\s*(\d{1,3}(,\d{3})*|\d+)\s*(k|thousand|lakh)?"#, options: .regularExpression) {
            var raw = String(prompt[match])
                .replacingOccurrences(of: "₹", with: "")
                .replacingOccurrences(of: "$", with: "")
                .replacingOccurrences(of: "€", with: "")
                .replacingOccurrences(of: "£", with: "")
                .replacingOccurrences(of: ",", with: "")
                .trimmingCharacters(in: .whitespaces)
            
            if raw.lowercased().hasSuffix("k") {
                raw = raw.replacingOccurrences(of: "k", with: "")
                if let val = Double(raw) { budget = val * 1000.0 }
            } else if raw.lowercased().hasSuffix("lakh") {
                raw = raw.replacingOccurrences(of: "lakh", with: "")
                if let val = Double(raw) { budget = val * 100000.0 }
            } else if let val = Double(raw), val >= 1000 {
                budget = val
            }
        }
        
        // 5. Trip Type
        let tripType: TripType = lower.contains("one way") ? .oneWay : .roundTrip
        
        // 6. Preferences
        var preferences: Set<TravelPreference> = [.nature, .relaxation]
        if lower.contains("adventure") || lower.contains("trek") || lower.contains("sport") {
            preferences.insert(.adventure)
        }
        if lower.contains("culture") || lower.contains("history") || lower.contains("heritage") || lower.contains("temple") {
            preferences.insert(.culture)
        }
        if lower.contains("food") || lower.contains("cuisine") || lower.contains("dining") || lower.contains("restaurant") {
            preferences.insert(.foodie)
        }
        if lower.contains("budget") || lower.contains("cheap") {
            preferences.insert(.budgetFriendly)
        }
        if lower.contains("luxury") || lower.contains("premium") || lower.contains("5 star") || lower.contains("5-star") {
            preferences.insert(.luxury)
        }
        if lower.contains("shop") || lower.contains("market") || lower.contains("bazaar") {
            preferences.insert(.shopping)
        }
        
        let req = TripRequest(
            origin: "Delhi",
            destination: destination,
            numberOfDays: days,
            travelersCount: travelers,
            groupType: groupType,
            budget: budget,
            currency: currency,
            tripType: tripType,
            preferences: preferences
        )
        AppLogger.shared.logGeminiResponse(
            action: "parseTripPrompt (Deterministic NLU)",
            model: "FallbackGeminiService",
            duration: 0.005,
            promptSnippet: prompt,
            responseSnippet: "Parsed destination: \(req.destination), days: \(req.numberOfDays), group: \(req.groupType.rawValue), budget: \(req.currency) \(Int(req.budget))",
            isFallback: true
        )
        return req
    }
    
    public func generateItineraryNarrative(for itinerary: TripItinerary, request: TripRequest) async throws -> String {
        let hotelTitle = itinerary.selectedHotel?.name ?? "handpicked accommodation"
        let transportTitle = itinerary.selectedTransportation?.title ?? "convenient transit"
        let travelerPhrase = request.travelersCount == 1 ? "solo traveler" : "\(request.travelersCount) guests (\(request.groupType.rawValue.lowercased()) dynamic)"
        
        let primaryHighlights = itinerary.days.prefix(2).flatMap { $0.activities }.prefix(3).map(\.place.name).joined(separator: ", ")
        let highlightsSnippet = primaryHighlights.isEmpty ? "top regional landmarks" : primaryHighlights
        
        let narrative = """
        Welcome to your tailored \(request.numberOfDays)-day \(request.destination) expedition! \
        Curated specifically for \(travelerPhrase) with a total allocated budget of \(request.currency) \(Int(request.budget)).

        You will be traveling comfortably via \(transportTitle) and staying at \(hotelTitle), which was scored highest by our on-device engine for safety, proximity, and budget fit. \
        Your schedule balances iconic attractions like \(highlightsSnippet) with scenic downtime, clustered geographically to keep daily transit smooth and relaxing.
        """
        AppLogger.shared.logGeminiResponse(
            action: "generateItineraryNarrative (Local Templates)",
            model: "FallbackGeminiService",
            duration: 0.005,
            promptSnippet: "Generating narrative for \(itinerary.destination)",
            responseSnippet: String(narrative.prefix(140)),
            isFallback: true
        )
        return GeminiWordLimitEnforcer.trimTo200Words(narrative)
    }
    
    public func handleConversationalModification(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) async throws -> ItineraryModificationResult {
        let lower = instruction.lowercased()
        var updated = currentItinerary
        var explanation = ""
        let nights = max(1, currentItinerary.numberOfDays - 1)
        
        if lower.contains("cheap") || lower.contains("budget") || lower.contains("less expensive") {
            if let currentHotel = currentItinerary.selectedHotel {
                let cheaperHotels = candidatePool.hotels.filter { $0.pricePerNight < currentHotel.pricePerNight }
                    .sorted { $0.pricePerNight < $1.pricePerNight }
                
                if let alternative = cheaperHotels.first {
                    updated.selectedHotel = alternative
                    let currentCost = currentHotel.totalCost(for: currentItinerary.travelersCount, nights: nights)
                    let newCost = alternative.totalCost(for: currentItinerary.travelersCount, nights: nights)
                    let savings = currentCost - newCost
                    explanation = "Swapped accommodation to '\(alternative.name)', saving \(currentItinerary.currency) \(Int(savings)) overall while maintaining high comfort."
                } else {
                    explanation = "Your current hotel '\(currentHotel.name)' is already the most budget-efficient option meeting all room capacity and safety criteria."
                }
            }
        } else if lower.contains("luxury") || lower.contains("upgrade") || lower.contains("premium") {
            if let currentHotel = currentItinerary.selectedHotel {
                let premiumHotels = candidatePool.hotels.filter { $0.pricePerNight > currentHotel.pricePerNight }
                    .sorted { $0.reviewScore > $1.reviewScore }
                
                if let alternative = premiumHotels.first {
                    updated.selectedHotel = alternative
                    explanation = "Upgraded stay to premium property '\(alternative.name)' (rated \(alternative.reviewScore)/5.0) featuring enhanced amenities."
                } else {
                    explanation = "'\(currentHotel.name)' is currently our top-tier accommodation candidate for your dates."
                }
            }
        } else if lower.contains("train") {
            if let trainOpt = candidatePool.transportOptions.first(where: { $0.mode == .train }) {
                updated.selectedTransportation = trainOpt
                explanation = "Updated transit to scenic railway route: '\(trainOpt.title)'. Enjoy relaxing valley vistas and comfortable seating."
            } else {
                explanation = "Railway options were already prioritized or unavailable for these exact dates."
            }
        } else if lower.contains("flight") {
            if let flightOpt = candidatePool.transportOptions.first(where: { $0.mode == .flight }) {
                updated.selectedTransportation = flightOpt
                explanation = "Upgraded transit to fastest flight connection: '\(flightOpt.title)'."
            } else {
                explanation = "No alternative direct flights found for these dates."
            }
        } else {
            explanation = "I've re-evaluated your itinerary with your preference for '\(instruction)' in mind. Your daily route and schedule remain fully optimized."
        }
        
        // Recalculate totals
        var cost = 0.0
        if let transport = updated.selectedTransportation {
            cost += transport.totalPrice(for: updated.travelersCount)
        }
        if let hotel = updated.selectedHotel {
            cost += hotel.totalCost(for: updated.travelersCount, nights: nights)
        }
        for day in updated.days {
            cost += day.activities.reduce(0.0) { $0 + ($1.place.entryFee * Double(updated.travelersCount)) }
        }
        updated.totalEstimatedCost = cost
        updated.updatedAt = Date()
        
        return ItineraryModificationResult(updatedItinerary: updated, aiExplanation: explanation)
    }
    
    public func recommendTrain(
        trains: [TrainCandidate],
        request: TripRequest
    ) async throws -> TrainRecommendationResult {
        guard !trains.isEmpty else {
            throw GeminiError.invalidResponse("No candidate trains provided")
        }
        
        let scored = trains.map { train -> (train: TrainCandidate, score: Double) in
            var score = 100.0
            score += max(0.0, 40.0 - (Double(train.durationMinutes) / 20.0))
            
            let cal = Calendar.current
            let depHour = cal.component(.hour, from: train.departureTime)
            if depHour >= 6 && depHour <= 10 {
                score += 25.0
            } else if depHour >= 11 && depHour <= 17 {
                score += 15.0
            } else if depHour >= 18 && depHour <= 22 {
                score += 20.0
            } else {
                score -= 20.0
            }
            
            let nameLower = train.trainName.lowercased()
            if nameLower.contains("vande bharat") {
                score += 35.0
            } else if nameLower.contains("shatabdi") || nameLower.contains("rajdhani") {
                score += 30.0
            } else if nameLower.contains("superfast") || train.trainNumber.hasPrefix("12") || train.trainNumber.hasPrefix("22") {
                score += 15.0
            }
            
            if request.groupType == .family {
                if train.availableClasses.contains("3A") || train.availableClasses.contains("2A") {
                    score += 15.0
                }
            } else if request.groupType == .couple {
                if train.availableClasses.contains("2A") || train.availableClasses.contains("EC") {
                    score += 15.0
                }
            }
            
            return (train, score)
        }
        
        let ranked = scored.sorted { $0.score > $1.score }.map(\.train)
        guard let best = ranked.first else {
            throw GeminiError.invalidResponse("Failed to rank candidate trains")
        }
        
        let recommendedClass: String
        let available = best.classFares.map(\.classCode)
        if request.groupType == .couple && available.contains("2A") {
            recommendedClass = "2A"
        } else if available.contains("3A") {
            recommendedClass = "3A"
        } else if available.contains("CC") {
            recommendedClass = "CC"
        } else if available.contains("2A") {
            recommendedClass = "2A"
        } else if let firstCode = available.first {
            recommendedClass = firstCode
        } else {
            recommendedClass = best.selectedClassCode ?? "3A"
        }
        
        let depTimeStr = DateFormatter.localizedString(from: best.departureTime, dateStyle: .none, timeStyle: .short)
        let arrTimeStr = DateFormatter.localizedString(from: best.arrivalTime, dateStyle: .none, timeStyle: .short)
        let hours = best.durationMinutes / 60
        let mins = best.durationMinutes % 60
        let durationStr = hours > 0 ? "\(hours)h \(mins)m" : "\(mins)m"
        
        let rationale = "Recommended '\(best.trainName)' as your best travel option. It provides an optimal departure at \(depTimeStr) arriving at \(arrTimeStr) (\(durationStr)), offering comfortable \(recommendedClass) accommodation balanced with budget efficiency for your \(request.travelersCount) \(request.groupType.rawValue) travelers."
        
        let topThree = Array(ranked.prefix(3).map(\.trainNumber))
        var altNotes: [String: String] = [:]
        
        if ranked.count > 1 {
            let second = ranked[1]
            let secondDep = DateFormatter.localizedString(from: second.departureTime, dateStyle: .none, timeStyle: .short)
            altNotes[second.trainNumber] = "Alternative departure at \(secondDep) with economical fares across \(second.classFares.map(\.classCode).joined(separator: "/"))."
        }
        if ranked.count > 2 {
            let third = ranked[2]
            let thirdDep = DateFormatter.localizedString(from: third.departureTime, dateStyle: .none, timeStyle: .short)
            altNotes[third.trainNumber] = "Secondary option departing at \(thirdDep) suitable if primary schedules conflict."
        }
        
        return TrainRecommendationResult(
            recommendedTrainNumber: best.trainNumber,
            recommendedClassCode: recommendedClass,
            rationale: rationale,
            topThreeTrainNumbers: topThree,
            alternativeNotes: altNotes
        )
    }
    
    public func recommendConnectingJourney(
        journeys: [TrainConnectingJourney],
        request: TripRequest
    ) async throws -> ConnectingJourneyRecommendationResult {
        guard !journeys.isEmpty else {
            throw GeminiError.invalidResponse("No candidate connecting journeys provided")
        }
        
        let scored = journeys.map { journey -> (journey: TrainConnectingJourney, score: Double) in
            var score = 100.0
            
            // Prefer layovers between 90 and 150 minutes (stress-free platform transfer)
            let layoverDiff = abs(journey.connection.layoverMinutes - 120)
            score += max(0.0, 50.0 - Double(layoverDiff) * 0.5)
            
            // Shorter duration
            score += max(0.0, 50.0 - (Double(journey.totalDurationMinutes) / 30.0))
            
            // Train category / speed
            let leg1 = journey.segments[0]
            let leg2 = journey.segments.count > 1 ? journey.segments[1] : leg1
            let name1 = leg1.trainName.lowercased()
            let name2 = leg2.trainName.lowercased()
            
            if name1.contains("shatabdi") || name1.contains("vande bharat") || name1.contains("rajdhani") {
                score += 25.0
            } else if name1.contains("superfast") || leg1.trainNumber.hasPrefix("12") || leg1.trainNumber.hasPrefix("22") {
                score += 15.0
            }
            if name2.contains("shatabdi") || name2.contains("vande bharat") || name2.contains("toy train") || name2.contains("himalayan") || name2.contains("shivalik") {
                score += 25.0
            } else if name2.contains("superfast") || leg2.trainNumber.hasPrefix("12") || leg2.trainNumber.hasPrefix("22") {
                score += 15.0
            }
            
            // Departure hour
            let cal = Calendar.current
            let depHour = cal.component(.hour, from: leg1.departureTime)
            if depHour >= 6 && depHour <= 22 {
                score += 20.0
            }
            
            return (journey, score)
        }
        
        let ranked = scored.sorted { $0.score > $1.score }.map(\.journey)
        guard let best = ranked.first else {
            throw GeminiError.invalidResponse("Failed to rank candidate connecting journeys")
        }
        
        let leg1 = best.segments[0]
        let leg2 = best.segments.count > 1 ? best.segments[1] : leg1
        let hubName = best.connection.stationName.components(separatedBy: " (").first ?? best.connection.stationName
        let leg1Class = leg1.selectedClassCode ?? leg1.seatClass
        let leg2Class = leg2.selectedClassCode ?? leg2.seatClass
        let dest = leg2.destinationStation.components(separatedBy: " (").first ?? leg2.destinationStation
        
        let rationale = "Best balance of total travel time, comfort and budget. Leg 1 (\(leg1.trainName)) connects smoothly at \(hubName) with a comfortable \(best.connection.formattedLayover) layover before \(leg2.trainName) to \(dest). Available in \(leg1Class) + \(leg2Class)."
        
        let topThree = Array(ranked.prefix(3).map(\.id))
        var altNotes: [String: String] = [:]
        
        if ranked.count > 1 {
            let second = ranked[1]
            let sLeg1 = second.segments[0]
            let sLeg2 = second.segments.count > 1 ? second.segments[1] : sLeg1
            let sHub = second.connection.stationName.components(separatedBy: " (").first ?? second.connection.stationName
            altNotes[second.id] = "Alternative via \(sHub) (\(second.connection.formattedLayover) layover) with \(sLeg1.trainName) and \(sLeg2.trainName)."
        }
        if ranked.count > 2 {
            let third = ranked[2]
            let tLeg1 = third.segments[0]
            let tLeg2 = third.segments.count > 1 ? third.segments[1] : tLeg1
            let tHub = third.connection.stationName.components(separatedBy: " (").first ?? third.connection.stationName
            altNotes[third.id] = "Secondary connection via \(tHub) (\(third.connection.formattedLayover) layover) with \(tLeg1.trainName) and \(tLeg2.trainName)."
        }
        
        return ConnectingJourneyRecommendationResult(
            recommendedJourneyId: best.id,
            rationale: rationale,
            topThreeJourneyIds: topThree,
            alternativeNotes: altNotes
        )
    }
}

// MARK: - Direct REST Client (Secondary Fallback)

// MARK: - Gemini REST Codable Models

public struct GeminiGenerateContentResponse: Codable, Sendable {
    public struct Candidate: Codable, Sendable {
        public struct Content: Codable, Sendable {
            public struct Part: Codable, Sendable {
                public let text: String?
            }
            public let parts: [Part]?
            public let role: String?
        }
        public let content: Content?
    }
    public struct ErrorPayload: Codable, Sendable {
        public let code: Int?
        public let message: String?
        public let status: String?
    }
    public let candidates: [Candidate]?
    public let error: ErrorPayload?
}

/// Direct Google Gemini REST API Client.
public final class GeminiAPIService: GeminiServiceProtocol, Sendable {
    public let modelName: String
    private let apiKey: String
    private let network: NetworkProtocol
    private let fallback: FallbackGeminiService
    
    public init(
        apiKey: String,
        modelName: String = "gemini-2.5-flash",
        network: NetworkProtocol = Network.shared,
        fallback: FallbackGeminiService = FallbackGeminiService()
    ) {
        self.apiKey = apiKey
        self.modelName = modelName
        self.network = network
        self.fallback = fallback
    }
    
    public convenience init(
        apiKey: String,
        modelName: String = "gemini-2.5-flash",
        session: URLSession,
        fallback: FallbackGeminiService = FallbackGeminiService()
    ) {
        self.init(apiKey: apiKey, modelName: modelName, network: Network(session: session), fallback: fallback)
    }
    
    public func parseTripPrompt(_ prompt: String) async throws -> TripRequest {
        let urlString = "https://generativelanguage.googleapis.com/v1beta/models/\(modelName):generateContent?key=\(apiKey)"
        guard let url = URL(string: urlString) else {
            return try await fallback.parseTripPrompt(prompt)
        }
        
        let requestBody: [String: Any] = [
            "contents": [
                [
                    "role": "user",
                    "parts": [
                        ["text": "Extract travel parameters from the user prompt: \(prompt)"]
                    ]
                ]
            ],
            "generationConfig": [
                "temperature": 0.1,
                "responseMimeType": "application/json",
                "responseSchema": [
                    "type": "OBJECT",
                    "properties": [
                        "destination": ["type": "STRING", "description": "Capitalized destination city or region name"],
                        "origin": ["type": "STRING", "description": "Origin city, defaults to 'Delhi' if unspecified"],
                        "numberOfDays": ["type": "INTEGER", "description": "Duration in days"],
                        "travelersCount": ["type": "INTEGER", "description": "Number of travelers"],
                        "groupType": [
                            "type": "STRING",
                            "enum": ["Solo", "Couple", "Friends", "Family", "Business"],
                            "description": "Dynamic of travel group"
                        ],
                        "budget": ["type": "NUMBER", "description": "Total trip budget"],
                        "currency": ["type": "STRING", "description": "Currency code e.g. INR, USD, EUR"],
                        "tripType": [
                            "type": "STRING",
                            "enum": ["roundTrip", "oneWay"]
                        ],
                        "preferences": [
                            "type": "ARRAY",
                            "items": ["type": "STRING"]
                        ]
                    ],
                    "required": ["destination", "numberOfDays", "travelersCount", "groupType", "budget", "currency"]
                ]
            ]
        ]
        
        guard let httpBody = try? JSONSerialization.data(withJSONObject: requestBody) else {
            return try await fallback.parseTripPrompt(prompt)
        }
        
        let startTime = Date()
        do {
            let req = Request(
                url: url,
                method: .post,
                headers: ["Content-Type": "application/json"],
                body: httpBody,
                timeoutInterval: 15.0
            )
            let response: GeminiGenerateContentResponse = try await network.perform(request: req)
            let elapsed = Date().timeIntervalSince(startTime)
            
            if let text = response.candidates?.first?.content?.parts?.first?.text {
                let cleaned = text.replacingOccurrences(of: "```json", with: "").replacingOccurrences(of: "```", with: "").trimmingCharacters(in: .whitespacesAndNewlines)
                if let jsonData = cleaned.data(using: .utf8),
                   let dict = try? JSONSerialization.jsonObject(with: jsonData) as? [String: Any],
                   let dest = dict["destination"] as? String {
                    let origin = dict["origin"] as? String ?? "Delhi"
                    let days = dict["numberOfDays"] as? Int ?? 5
                    let travelers = dict["travelersCount"] as? Int ?? 4
                    let budget = dict["budget"] as? Double ?? 50000.0
                    let currency = dict["currency"] as? String ?? "INR"
                    let groupRaw = dict["groupType"] as? String ?? "Friends"
                    let groupType = GroupType(rawValue: groupRaw) ?? .friends
                    
                    let parsed = TripRequest(
                        origin: origin,
                        destination: dest,
                        numberOfDays: days,
                        travelersCount: travelers,
                        groupType: groupType,
                        budget: budget,
                        currency: currency
                    )
                    AppLogger.shared.logGeminiResponse(
                        action: "parseTripPrompt (Direct REST)",
                        model: modelName,
                        duration: elapsed,
                        promptSnippet: prompt,
                        responseSnippet: "Parsed destination: \(parsed.destination), days: \(parsed.numberOfDays), budget: \(parsed.currency) \(Int(parsed.budget))",
                        isFallback: false
                    )
                    return parsed
                }
            }
        } catch {
            AppLogger.shared.info("[GeminiAPIService] parseTripPrompt REST failed (\(error.localizedDescription)), falling back", category: .gemini)
        }
        
        return try await fallback.parseTripPrompt(prompt)
    }
    
    public func generateItineraryNarrative(for itinerary: TripItinerary, request: TripRequest) async throws -> String {
        let prompt = """
        Write a concise, captivating narrative under 200 words for a \(request.numberOfDays)-day trip to \(request.destination) for \(request.travelersCount) \(request.groupType.rawValue.lowercased()) with total budget \(request.currency) \(Int(request.budget)).
        Selected hotel: \(itinerary.selectedHotel?.name ?? "Central Hotel").
        Selected transit: \(itinerary.selectedTransportation?.title ?? "Express Transit").
        Highlight local atmosphere and pacing. Do NOT invent prices or confirmation codes.
        CRITICAL CONSTRAINT: Keep your entire response strictly under 200 words.
        """
        
        let urlString = "https://generativelanguage.googleapis.com/v1beta/models/\(modelName):generateContent?key=\(apiKey)"
        guard let url = URL(string: urlString) else {
            return try await fallback.generateItineraryNarrative(for: itinerary, request: request)
        }
        
        let requestBody: [String: Any] = [
            "contents": [["role": "user", "parts": [["text": prompt]]]]
        ]
        guard let httpBody = try? JSONSerialization.data(withJSONObject: requestBody) else {
            return try await fallback.generateItineraryNarrative(for: itinerary, request: request)
        }
        
        let startTime = Date()
        do {
            let req = Request(
                url: url,
                method: .post,
                headers: ["Content-Type": "application/json"],
                body: httpBody,
                timeoutInterval: 15.0
            )
            let response: GeminiGenerateContentResponse = try await network.perform(request: req)
            let elapsed = Date().timeIntervalSince(startTime)
            
            if let text = response.candidates?.first?.content?.parts?.first?.text {
                let narrative = GeminiWordLimitEnforcer.trimTo200Words(text.trimmingCharacters(in: .whitespacesAndNewlines))
                AppLogger.shared.logGeminiResponse(
                    action: "generateItineraryNarrative (Direct REST)",
                    model: modelName,
                    duration: elapsed,
                    promptSnippet: "Itinerary narrative for \(itinerary.destination)",
                    responseSnippet: narrative,
                    isFallback: false
                )
                return narrative
            }
        } catch {
            AppLogger.shared.info("[GeminiAPIService] generateItineraryNarrative REST failed (\(error.localizedDescription)), falling back", category: .gemini)
        }
        
        return try await fallback.generateItineraryNarrative(for: itinerary, request: request)
    }
    
    public func handleConversationalModification(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) async throws -> ItineraryModificationResult {
        return try await fallback.handleConversationalModification(
            instruction: instruction,
            currentItinerary: currentItinerary,
            candidatePool: candidatePool
        )
    }
    
    public func recommendTrain(
        trains: [TrainCandidate],
        request: TripRequest
    ) async throws -> TrainRecommendationResult {
        return try await fallback.recommendTrain(trains: trains, request: request)
    }
    
    public func recommendConnectingJourney(
        journeys: [TrainConnectingJourney],
        request: TripRequest
    ) async throws -> ConnectingJourneyRecommendationResult {
        return try await fallback.recommendConnectingJourney(journeys: journeys, request: request)
    }
}

// MARK: - Hybrid Facade (Smart Priority Router)

/// Smart facade routing between Firebase AI SDK, direct REST, and offline reasoning based on runtime configuration.
public final class HybridGeminiService: GeminiServiceProtocol, Sendable {
    public let firebaseService: FirebaseGeminiService
    public let fallbackService: FallbackGeminiService
    public let modelName: String
    
    public init(
        modelName: String = "gemini-2.5-flash",
        fallbackService: FallbackGeminiService = FallbackGeminiService()
    ) {
        self.modelName = modelName
        self.fallbackService = fallbackService
        self.firebaseService = FirebaseGeminiService(modelName: modelName, fallback: fallbackService)
    }
    
    public var activeService: GeminiServiceProtocol {
        // 1. If user explicitly provided a custom Gemini key in settings, prioritize direct REST with their personal key
        if AppConfiguration.shared.hasUserCustomGeminiKey,
           let customKey = AppConfiguration.shared.geminiApiKey,
           customKey.count > 10 {
            return GeminiAPIService(apiKey: customKey, modelName: modelName, fallback: fallbackService)
        }
        
        if FirebaseApp.app() != nil || AppConfiguration.shared.isGeminiConfigured {
            return firebaseService
        }
        
        if let key = AppConfiguration.shared.geminiApiKey, !key.isEmpty, key.count > 10 {
            return GeminiAPIService(apiKey: key, modelName: modelName, fallback: fallbackService)
        }
        
        return fallbackService
    }
    
    /// Tests live cloud connectivity to Google Gemini and returns diagnostic information.
    public func testCloudConnection() async -> (isLive: Bool, title: String, message: String) {
        guard let key = AppConfiguration.shared.geminiApiKey, key.count > 10 else {
            return (false, "No Key Configured", "Add a Gemini API key in Profile or configure GoogleService-Info.plist to enable live cloud AI.")
        }
        
        let urlString = "https://generativelanguage.googleapis.com/v1beta/models/\(modelName):generateContent?key=\(key)"
        guard let url = URL(string: urlString) else {
            return (false, "Invalid Endpoint URL", "Could not format Gemini endpoint URL.")
        }
        
        let body: [String: Any] = [
            "contents": [["parts": [["text": "ping"]]]]
        ]
        let req = Request(
            url: url,
            method: .post,
            headers: ["Content-Type": "application/json"],
            body: try? JSONSerialization.data(withJSONObject: body),
            timeoutInterval: 8.0
        )
        
        let startTime = Date()
        do {
            let (data, http, elapsed) = try await Network.shared.performRaw(request: req)
            
            if http.statusCode == 200 {
                AppLogger.shared.logAPISuccess(
                    endpoint: "generativelanguage.googleapis.com (ping test)",
                    method: "POST",
                    statusCode: 200,
                    duration: elapsed,
                    payloadSummary: "Gemini connection verified"
                )
                return (true, "Live Gemini Connected", "Successfully connected to Google Gemini Cloud API! Real-time streaming and dynamic generation are active.")
            } else if http.statusCode == 403 {
                AppLogger.shared.logAPIError(
                    endpoint: "generativelanguage.googleapis.com (ping test)",
                    method: "POST",
                    statusCode: 403,
                    error: GeminiError.networkError("Permission denied / API disabled (403)"),
                    duration: elapsed
                )
                let projectId = AppConfiguration.shared.firebaseProjectId ?? "your project"
                if let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                   let errorDict = json["error"] as? [String: Any],
                   let msg = errorDict["message"] as? String,
                   (msg.contains("has not been used in project") || msg.contains("disabled")) {
                    return (false, "API Disabled in Google Cloud", "The Gemini API is not enabled on Google Cloud project '\(projectId)'. Visit console.developers.google.com to enable 'generativelanguage.googleapis.com' or enter a free API key from aistudio.google.com.")
                }
                return (false, "Permission Denied (403)", "Google Cloud returned 403 Forbidden. Enable Gemini API in project '\(projectId)' or paste a free key from aistudio.google.com.")
            } else {
                AppLogger.shared.logAPIError(
                    endpoint: "generativelanguage.googleapis.com (ping test)",
                    method: "POST",
                    statusCode: http.statusCode,
                    error: GeminiError.networkError("HTTP status \(http.statusCode)"),
                    duration: elapsed
                )
                return (false, "HTTP Error \(http.statusCode)", "Server responded with status \(http.statusCode). Offline fallback is active.")
            }
        } catch {
            let elapsed = Date().timeIntervalSince(startTime)
            AppLogger.shared.logAPIError(
                endpoint: "generativelanguage.googleapis.com (ping test)",
                method: "POST",
                error: error,
                duration: elapsed
            )
            return (false, "Offline / Network Error", error.localizedDescription)
        }
    }
    
    public func parseTripPrompt(_ prompt: String) async throws -> TripRequest {
        return try await activeService.parseTripPrompt(prompt)
    }
    
    public func generateItineraryNarrative(for itinerary: TripItinerary, request: TripRequest) async throws -> String {
        return try await activeService.generateItineraryNarrative(for: itinerary, request: request)
    }
    
    public func generateItineraryNarrativeStream(for itinerary: TripItinerary, request: TripRequest) async throws -> AsyncThrowingStream<String, Error> {
        return try await activeService.generateItineraryNarrativeStream(for: itinerary, request: request)
    }
    
    public func handleConversationalModification(
        instruction: String,
        currentItinerary: TripItinerary,
        candidatePool: FilteredCandidatesBundle
    ) async throws -> ItineraryModificationResult {
        return try await activeService.handleConversationalModification(
            instruction: instruction,
            currentItinerary: currentItinerary,
            candidatePool: candidatePool
        )
    }
    
    public func recommendTrain(
        trains: [TrainCandidate],
        request: TripRequest
    ) async throws -> TrainRecommendationResult {
        return try await activeService.recommendTrain(trains: trains, request: request)
    }
    
    public func recommendConnectingJourney(
        journeys: [TrainConnectingJourney],
        request: TripRequest
    ) async throws -> ConnectingJourneyRecommendationResult {
        return try await activeService.recommendConnectingJourney(journeys: journeys, request: request)
    }
}
